branches:
  only:
    - master
    - staging
    - trying

dist: trusty
sudo: false

addons:
  apt:
    packages:
    - gcc
    - g++
    - libssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev
    - pkg-config

language: rust
rust:
  - nightly-2018-11-18

matrix:
  allow_failures:
    - rust: nightly

cache:
  directories:
  - "$HOME/.cargo"
  - "$HOME/.local"
  - "$TRAVIS_BUILD_DIR/target"

env:
  global:
  - DEADLINKS_VERS=0.3.0
  - RUSTFLAGS="-C link-dead-code"
  - RUST_LOG=off

install:
- cargo install --list
- cd $TRAVIS_BUILD_DIR
- cargo update

script: skip

jobs:
  include:
  - stage: test
    env:
    - FEATURE=test
    rust: nightly-2018-11-18
    script:
    - cargo test --verbose --all

  - stage: test
    env:
    - FEATURE=test
    rust: nightly
    script:
    - cargo test --verbose --all

  - stage: quality
    env:
    - FEATURE=non-fatal-checks
    install:
    - cargo-deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
    script:
    - cargo doc --no-deps && cargo deadlinks --dir target/doc || true

  - stage: quality
    env:
    - FEATURE=clippy
    rust: nightly-2018-11-18
    install:
    - rustup component add clippy-preview
    script:
    - cargo clippy -- -D warnings
