[package]
name = "incrust"
version = "0.1.4"
authors = ["Alexander Irbis <irbis.labs@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Template engine inspired by Jinja2"
repository = "https://github.com/alexander-irbis/incrust"
readme = "README.md"
#documentation = ""
keywords = ["template", "jinja2", "django", "twig", "swig"]
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
]
#build = "build.rs"
publish = true


[dependencies]
clippy          = { version = "0.0", optional = true }
marksman_escape = "0.1.2"
log             = "0.3"
maplit          = "0.1"
nom             = "1.2"

[features]
default         = []
verbose         = ["clippy"]
quiet           = []
